config/routes.rb
Rails.application.routes.draw do


  root 'sessions#root'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'  
  get '/signup', to: 'readers#new'
  post '/signup', to: 'readers#create'

  get '/readers/:id/recom', to: 'books#recom'
  get '/readers/:id/foll', to: 'readers#foll'
  post '/readers/:id/foll', to: 'readers#foll'
  get '/readers/:id/mybooks', to: 'books#mybooks'
  post '/readers/:id/mybooks', to: 'books#mybooks'


  resources :author_books
  resources :reader_books
  resources :recommendations
  resources :relationships
  resources :readers
  resources :authors
  resources :books
  resources :reviews,          only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reader.rb
class Reader < ApplicationRecord
  after_initialize :set_defaults, unless: :persisted?
  # The set_defaults will only work if the object is new

  def comCount(current_reader)
    @common = 0
    self.reader_books.each {|x|
      b = x.book
      if ReaderBook.find_by(reader: current_reader, book: b)
        @common += 1
      end 
    }  
    return @common
  end

  def set_defaults
    self.book_count  ||= 0
  end

  def self.search(search)
    where("name ILIKE ?", "%#{search}%") 
  end

  has_many :reader_books
  has_many :books, through: :reader_books

  has_many :reviews, dependent: :destroy
  has_many :books, through: :reviews

  has_many :recommendations, dependent: :destroy
  has_many :books, through: :recommendations

  has_many :active_relationships, class_name:  "Relationship",
           foreign_key: "follower_id",
           dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
           foreign_key: "followed_id",
           dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

  before_save { email.downcase! }
  
  validates :name,  presence: true, length: { maximum: 50 }, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
             uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, if: ->(r) { r.password.present? }

   # Returns the hash digest of the given string.
  def Reader.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController
  before_action :set_reader, only: [:show, :edit, :update, :destroy]

  def comCount(current_reader)
    @common = 0
    @reader.books.each {|x|
      if current_reader.books.include?(x)
        @common += 1
      end 
    }  
    return @common
  end

  def index
    if !logged_in?
      store_location
      redirect_to root_path
      return
    end
    @readers = Reader.all
    @found = true
    if params[:search]
      @readers = Reader.search(params[:search]).order("name")
      if @readers.empty?
        @found = false
        @readers = Reader.all.order('name')
      end
    else
      @readers = Reader.all.order('name')
    end
  end

  def new
    if logged_in?
      redirect_to root_path 
      return
    end
  	@reader = Reader.new
  end

  def foll
    if !logged_in?
      store_location
      redirect_to root_path 
      return
    end
    @reader = Reader.find(params[:id])
    @readers = []
    @fount = true
    @found = true

    if (['Followings']).include?(params[:commit])
      Reader.all.each { |r| 
        if @reader.following?(r)
          @readers << r;
        end
      }
    else
      Reader.all.each { |r| 
        if r.following?(@reader)
          @readers << r;
        end
      }
    end


    if @readers.empty?
      @fount = false        #я не ошибся, там правла t
    end
    @save_readers = @readers.clone

      if params[:search]
        @readers.each { |x|
          if !x.name.include?(params[:search])
            @readers.delete(x)
          end
        }
        if @readers.empty?
          @found = false
          @readers = @save_readers.clone
        end
      end
  end

  def root
    redirect_to login_readers_path
  end
  
  def show
    if !logged_in?
      store_location
      redirect_to root_path 
      return
    end
    @reader = Reader.find(params[:id])
  end

  def edit
    if check==0
      return
    end
    @reader = Reader.find(params[:id])
    if !logged_in?
      store_location
      redirect_to root_path 
    elsif current_reader.name != "admin" and current_reader.name != @reader.name
      redirect_to root_path 
    end
  end

  def update
    if check==0
      return
    end
    @reader = Reader.find(params[:id])
 
    if @reader.update(reader_params)
          redirect_to @reader
    else
          render 'edit'
    end
  end

  def create
    @reader = Reader.new(reader_params)
 
      if @reader.save
        log_in @reader
        redirect_to @reader
      else
        render 'new'
      end
  end

  def destroy
    if check==0
      return
    end

    @reader = Reader.find(params[:id])
    @reader.destroy
 
    redirect_to readers_path
  end
 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reader
      @reader = Reader.find(params[:id])
    end

    def reader_params
      params
        .require(:reader)
        .permit(:name, :email, :password, :password_confirmation)                 
    end

    def check
      if !logged_in?
        store_location
        redirect_to root_path 
        return 0
      elsif current_reader.name != "admin" and current_reader.name != @reader.name
        redirect_to root_path 
        return 0
      else
        return 1
      end
    end
end

app/helpers/readers_helper.rb
module ReadersHelper
end

app/views/readers/edit.html.erb
<% if @reader==current_reader %>
  <% provide(:title, 'Edit profile') %>
<% else %>
  <% provide(:title, "Edit " + @reader.name) %>
<% end %>

<h1>Edit profile</h1>
<%= form_for :reader, url: reader_path(@reader), method: :patch do |f| %>

  <div class="col-md-4 col-md-offset-4">
    <%= render 'shared/error_messages' %>
    <p>
      <%= f.label :username %><br>
      <%= f.text_field :name, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :email %><br>
      <%= f.email_field :email, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :old_password %><br>
      <%= f.password_field :old_password, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :new_password %><br>
      <%= f.password_field :password_digest, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :password_confirmation, "Confirmation" %><br>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </p>
  </div>
  <div class="col-md-4 col-md-offset-4">
    <p>
      <%= f.submit "Save", class: "btn flat_button" %>
    </p>
  <div class="center"><%= link_to 'Discard and go back', readers_path, class: "link" %></div>
  <% end %>
  </div>

app/views/readers/foll.html.erb
<% if @reader==current_reader %>
  <% provide(:title, 'Your followings') %>
<% else %>
  <% provide(:title, @reader.name+"'s followings") %>
<% end %>

<p id="notice"><%= notice %></p>
  <div class="main">
    <h1>Followers and Followings</h1>
    <div class="row">
        <%= form_tag("/readers/#{@reader.id}/foll", :method => "get", id: "search-form") do %>
        <div class="col-md-8 inline">
        <%= text_field_tag :search, params[:search], placeholder: "Whom are you looking for?", class: 'form-control textfield' %>
      </div>
      <div class="col-md-4 inline">
        <%= submit_tag "Search", class: "btn flat_button" %>
              </div>
        <% end %>
    </div>

    <%= form_for (:reader) do |f| %>
      <div class="row">
          <div class="col-md-6 inline"> <%= f.submit :'Followers', class: "btn flat_button books" %> </div>
          <div class="col-md-6 inline"> <%= f.submit :'Followings', class: "btn flat_button books" %> </div>
      </div>
    <% end %>

    <% if !@found %>
      <p>There are no readers containing the term(s) <%= params[:search] %>. 
      </p>
    <% end %>
    <% if !@fount %>
      <p id="nofount">There are no readers with chosen status.</p>
    <% end %> 

    <p></p>

    <div class="table_headings">
      <div class="row">
        <div class="col-md-6 inline">Name</div>
        <div class="col-md-2 inline">Books read</div>
      </div>
    </div>
    <div class="table_items">
      <% @readers.each do |reader| %>
      <div class="row">
        <div class="col-md-6 inline"><%= link_to reader.name, reader, class: "link" %></div>
        <div class="col-md-2 inline"><%= reader.book_count %></div>
      </div>
      <% end %>
    </div>
  </div>

app/views/readers/index.html.erb
<% provide(:title, 'Readers') %>

<p id="notice"><%= notice %></p>
  <div class="main">
<h1>Readers</h1>
<div class="row">
    <%= form_tag(readers_path, :method => "get", id: "search-form") do %>
    <div class="col-md-8 inline">
      <%= text_field_tag :search, params[:search], placeholder: "Whom are you looking for?", class: 'form-control textfield' %>
  </div>
    <div class="col-md-4 inline">
      <%= submit_tag "Search", class: "btn flat_button" %>
        </div>
    <% end %>
  <% if !@found %>
    <div id="notfoundmessage"><p>There are no readers containing the term(s) <%= params[:search] %>. Here is the list of all readers</p></div>
  <% end %>

<div class="table_headings">
  <div class="col-md-5 inline">Name</div>
  <div class="col-md-3 inline">Books read</div>
  <div class="col-md-3 inline">Common books</div>
</div>
<div class="table_items">
  <% @readers.each do |reader| %>
  <div class="col-md-5 inline"><%= link_to reader.name, reader, class: "link" %></div>
  <div class="col-md-3 inline"><%= reader.book_count %></div>
  <div class="col-md-3 inline"><%= reader.comCount(current_reader) %></div>

    <% if current_reader.name == "admin" %>
      <div class="col-md-1 inline">
        <div class="inline">
          <%= link_to edit_reader_path(reader) do %>
            <span class="glyphicon glyphicon-pencil right"></span>
          <% end %>
        </div>
        <div class="inline">
        <%= link_to reader_path(reader),
                method: :delete,
                data: { confirm: 'Are you sure?' } do %>
          <span class="glyphicon glyphicon-trash right"></span>
          <% end %>
        </div>

      </div>
    <% end %>
  <% end %>
</div>
<br>
</div>
</div>
<br>

app/views/readers/new.html.erb
<% provide(:title, "Sign up") %>
<div class="col-md-8 col-md-offset-2">
<h1>Sign up</h1>

<div class="row">
    <%= form_for(:reader, url: readers_path) do |f| %>
      <%= render 'shared/error_messages' %>
      
      <p>
        <strong>Username</strong><br>
        <%= f.text_field :name, class: 'form-control textfield' %>
      </p>

      <p>
        <strong>Email</strong><br>
        <%= f.email_field :email, class: 'form-control textfield' %>
      </p>

      <p>
        <strong>Password</strong><br>
        <%= f.password_field :password, class: 'form-control textfield' %>
      </p>

      <p>
        <strong>Password confirmation</strong><br>
        <%= f.password_field :password_confirmation, class: 'form-control textfield' %>
      </p>
      <%= f.submit "Signing Up", class: "btn flat_button" %>
    <% end %>
  <br>
  </div>
</div>

app/views/readers/show.html.erb
<% provide(:title, @reader.name) %>
  <div class="main">
    <div class="center">
      <h1 class="profile_style"><%= @reader.name %></h1>
      <h2 class="profile_style">'s profile</h2>
    </div>
    <br>
    <p>
      <strong>Email:</strong>
      <%= @reader.email %>
      <% if @reader==current_reader or current_reader.name=="admin" %>
        <%= link_to edit_reader_path(@reader) do %>
          <span class="glyphicon glyphicon-edit"></span>
        <% end %>
      <% end %>
    </p>
    <p>
      <% if @reader==current_reader %>
        <%= link_to "My books", { controller: 'books', action: 'mybooks' }, class: "link" %>
      <% else %>
        <%= link_to "Books", { controller: 'books', action: 'mybooks' }, class: "link" %>
      <% end %>
    </p>

    <p>
      <%= link_to "Followers/followings", { controller: 'readers', action: 'foll' }, class: "link" %>
    </p>
    <p>
      <%= link_to "Recommendations", { controller: 'books', action: 'recom' }, class: "link" %>
    </p>

    <% unless current_reader == @reader %>
      <div class="row">
        <% unless current_reader.following?(@reader) %>
            <div class="col-md-8 left"><p><i>Have simular preferences?</i> Follow this reader!</p></div>
            <%= form_for @reader.active_relationships.build do |f| %>
              <%= f.hidden_field :reader_id, value: @reader.id %>
              <div class="col-md-4"><i><%= f.submit :'Follow', class: "btn flat_button recommend" %></i></div>
            <% end %>
        <% else %>
          <div class="col-md-8 left"><p><i>Different preferences?</i> Unfollow this reader!</p></div>


            <%= form_for current_reader.active_relationships.find_by!(followed: @reader) do |f| %>
              <%= f.hidden_field :reader_id, value: @reader.id %>
              <div class="col-md-4"><i><%= f.submit :'Unfollow', class: "btn flat_button recommend" %></i></div>
            <% end %>
        <% end %>
      </div>
    <% end %>
  </div>