config/routes.rb
Rails.application.routes.draw do


  root 'sessions#root'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'  
  get '/signup', to: 'readers#new'
  post '/signup', to: 'readers#create'

  get '/readers/:id/recom', to: 'books#recom'
  get '/readers/:id/foll', to: 'readers#foll'
  post '/readers/:id/foll', to: 'readers#foll'
  get '/readers/:id/mybooks', to: 'books#mybooks'
  post '/readers/:id/mybooks', to: 'books#mybooks'


  resources :author_books
  resources :reader_books
  resources :recommendations
  resources :relationships
  resources :readers
  resources :authors
  resources :books
  resources :reviews,          only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
class Author < ApplicationRecord
  after_initialize :set_defaults, unless: :persisted?
  # The set_defaults will only work if the object is new

  def set_defaults
    self.rating_average  ||= 0
  end

	has_many :author_books
  has_many :books, through: :author_books


  validates :name, presence: true, length: { maximum: 100 }
  validates_format_of :website, :allow_blank => true, :with => URI::regexp


	def self.search(search)
	  where("name ILIKE ?", "%#{search}%") 
	end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  def index
    @authors = Author.all
    @found = true
    if params[:search]
      @authors = Author.search(params[:search]).order("name")
      if @authors.empty?
        @found = false
        @authors = Author.all.order('name')
      end
    else
      @authors = Author.all.order('name')
    end
  end


  # GET /authors/new
  def new
    if check==0
      return
    end
    @author = Author.new
  end



	def show
		@author = Author.find(params[:id])

    @books = []
    Book.all.each { |b| 
      if b.author_books.find_by(author: @author)
        @books << b;
      end
    }
    @save_books = @books.clone 

    @found = true
      if params[:search]
        @books.each { |x|
          if !x.name.include?(params[:search])
            @books.delete(x)
          end
        }
        if @books.empty?
          @found = false
          @books = @save_books
        end
      end
	end

	def edit
    if check==0
      return
    end
    	@author = Author.find(params[:id])
  end



  def update
    if check==0
      return
    end
    @author = Author.find(params[:id])
    if @author.update(author_params)
      redirect_to @author
    else
      render 'edit'
    end
  end

	def create
    if check==0
      return
    end
		@author = Author.new(author_params)
  	
    if @author.save
  		redirect_to @author
  	else
  		render 'new'
  	end
	end

	def destroy
    if check==0
      return
    end
    @author = Author.find(params[:id])
    @author.destroy
 
	  redirect_to authors_path
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :website, :country, :bio, :rating_average)
    end
 
    def check
      if !logged_in?
        store_location
        redirect_to root_path 
        return 0
      elsif current_reader.name != "admin"
        redirect_to root_path 
        return 0
      else
        return 1
      end
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/edit.html.erb
<% provide(:title, "Edit" + @author.name) %>

<h1>Editing <%= @author.name %>'s info </h1>
 
<div class="row">
    <%= form_for :author, url: author_path(@author), method: :patch do |f| %>
      <% if @author.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@author.errors.count, "error") %> prohibited
            this author from being saved:
          </h2>
          <ul>
            <% @author.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <p>
        <%= f.label :name %><br>
        <%= f.text_field :name, class: "textfield" %>
      </p>
      <p>
        <%= f.label :country %><br>
        <%= f.text_field :country, class: "textfield" %>
      </p>
      <p>
        <%= f.label :website %><br>
        <%= f.text_field :website, class: "textfield"%>
      </p> 
      <p>
        <%= f.label :biography %><br>
        <%= f.text_area :bio, :rows => 10, class: "form-control textfield" %>
      </p>
      <p>
        <%= f.submit 'Save', class: "btn flat_button" %>
      </p>     
  <div class="center"><%= link_to 'Discard and go back', authors_path, class: "link" %></div>
  <% end %>
  </div>

app/views/authors/index.html.erb
<% provide(:title, 'Authors') %>

<p id="notice"><%= notice %></p>
  <div class="main">
  <h1>Authors</h1>
  <div class="row">
      <%= form_tag(authors_path, :method => "get", id: "search-form") do %>
      <div class="col-md-8 inline">
        <%= text_field_tag :search, params[:search], placeholder: "Whom are you looking for?", class: 'form-control textfield' %>
      </div>
      <div class="col-md-4 inline">
        <%= submit_tag "Search", class: "btn flat_button" %>
      </div>
      <% end %>
  </div>
    <% if !@found %>
    <div id="notfoundmessage"><p>There are no authors containing the term(s) <%= params[:search] %>. Here is the list of all authors</p></div>
    <% end %>
    <div class="table_headings">
      <div class="row">
        <div class="col-md-3 inline">Name</div>
        <div class="col-md-2 inline">Rating</div>
        <div class="col-md-2 inline">Country</div>
        <div class="col-md-4 inline">Website</div>
      </div>
    </div>
  <div class="table_items">
  <% @authors.each do |author| %>
    <div class="row">
      <div class="col-md-3 inline"><%= link_to author.name, author, class: "link" %></div>
      <div class="col-md-2 inline"><%= author.rating_average.round(2) %></div>
      <div class="col-md-2 inline"><%= author.country %></div>
      <% if logged_in? %>
        <% if current_reader.name == "admin" %>
          <div class="col-md-4 inline"><%= link_to author.website, author.website, class: "link" %></div>
          <div class="col-md-1 inline">
            <div class="inline">
              <%= link_to edit_author_path(author) do %>
                <span class="glyphicon glyphicon-pencil right"></span>
              <% end %>
            </div>
            <div class="inline">
              <%= link_to author_path(author),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash right"></span>
              <% end %>
            </div>
          </div>
        <% else %>
          <div class="col-md-4 inline"><%= link_to author.website, author.website, class: "link" %></div>
        <% end %>
      <% else %>
        <div class="col-md-4 inline"><%= link_to author.website, author.website, class: "link" %></div>
      <% end %>
    </div>
  <% end %>
  </div>
</div>

app/views/authors/new.html.erb
<% provide(:title, "New Author") %>

<h1>New Author</h1>
  <%= form_for :author, url: authors_path do |f| %>
    <p class:>
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control textfield" %>
    </p>
   
    <p>
      <%= f.label :biography %><br>
      <%= f.text_area :bio, :rows => 10, class: "form-control textfield" %>
    </p>

    <p>
      <%= f.label :country %><br>
      <%= f.text_field :country, class: "form-control textfield" %>
    </p>

    <p>
      <%= f.label :website %><br>
      <%= f.text_field :website, class: "form-control textfield" %>
    </p>
   
    <p>
      <%= f.submit :'Add author', class: "btn flat_button" %>
    </p>
  <% end %>

app/views/authors/show.html.erb
<% provide(:title, @author.name) %>
  <div class="main">
    <h1><%= @author.name %>
      <% if logged_in? %>
      <% if current_reader.name=="admin" %>
        <div class="inline">
          <p>
          <%= link_to edit_author_path(@author) do %>
            <span class="glyphicon glyphicon-edit"></span>
          <% end %>
        </p>
        </div>
        <% end %>
      <% end %>
    </h1>
    <h3 class="info">Bio:</h3>
    <p class="bio"><%= @author.bio %></p>
    <p>
      <h3 class="inline info">Country:</h3>
      <h3 class="inline"><%= @author.country %></h3>
    </p>
    <div class="inline">
      <h3 class="info">Website:
      <%= link_to @author.website, @author.website, class: "link" %></h3>
    </div>
    <h1>Books of author</h1>
    <div class="row">
        <%= form_tag("/authors/#{@author.id}", :method => "get", id: "search-form") do %>
        <div class="col-md-8 inline">
        <%= text_field_tag :search, params[:search], placeholder: "What are you looking for?", class: 'form-control textfield' %>
      </div>
      <div class="col-md-4 inline">
        <%= submit_tag "Search", class: "btn flat_button" %>
        </div>
        <% end %>
    </div>
    
    <% if !@found %>
      <p id="notfoundmessage">There are no books containing the term(s) <%= params[:search] %>. Here is the list of all author's books</p>
    <% end %>

    <div class="table_headings">
      <div class="row">
        <div class="col-md-4 inline">Name</div>
        <div class="col-md-1 inline">Year</div>
        <div class="col-md-2 inline">ISBN</div>
        <div class="col-md-2 inline">Genre</div>
        <div class="col-md-2 inline center">Rating</div>
      </div>
    </div>
    <div class="table_items">
      <% @books.each do |book| %>
        <div class="row">
          <div class="col-md-4 inline"><%= link_to book.name, book, class: "link" %></div>
          <div class="col-md-1 inline"><%= book.year %></div>
          <div class="col-md-2 inline"><%= book.ISBN %></div>
          <div class="col-md-2 inline"><%= book.genre %></div>
          <div class="col-md-2 inline center"><%= book.rating_average.round(2) %></div>
        </div>
      <% end %>
    </div>
  </div>
      <br>