config/routes.rb
Rails.application.routes.draw do


  root 'sessions#root'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'  
  get '/signup', to: 'readers#new'
  post '/signup', to: 'readers#create'

  get '/readers/:id/recom', to: 'books#recom'
  get '/readers/:id/foll', to: 'readers#foll'
  post '/readers/:id/foll', to: 'readers#foll'
  get '/readers/:id/mybooks', to: 'books#mybooks'
  post '/readers/:id/mybooks', to: 'books#mybooks'


  resources :author_books
  resources :reader_books
  resources :recommendations
  resources :relationships
  resources :readers
  resources :authors
  resources :books
  resources :reviews,          only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  after_initialize :set_defaults, unless: :persisted?
  # The set_defaults will only work if the object is new

  def set_defaults
    self.rating_amount  ||= 0
    self.rating_average  ||= 0
  end

  def self.search(search)
    where("name ILIKE ?", "%#{search}%") 
  end

  has_many :reader_books
  has_many :readers, through: :reader_books

  has_many :reviews, dependent: :destroy
  has_many :readers, through: :reviews

  has_many :recommendations, dependent: :destroy
  has_many :readers, through: :recommendations

  has_many :author_books
  has_many :authors, through: :author_books

  	validates :name, presence: true, length: {maximum: 255}
    validates :year, :allow_blank => true, inclusion: { in: 1000..Date.today.year } #умовно від 1000 року видання

  	validates :ISBN, :allow_blank => true, uniqueness: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.all
    @found = true
    if params[:search]
      @books = Book.search(params[:search]).order("name")
      if @books.empty?
        @found = false
        @books = Book.all.order('name')
      end
    else
      @books = Book.all.order('name')
    end
  end

  def recom
    if !logged_in?
      store_location
      redirect_to root_path
      return
    end
    @reader = Reader.find(params[:id])
    @books = []
    Reader.all.each{ |r|
      if @reader.following?(r)
        @read = r
        Book.all.each { |b| 
          if b.recommendations.find_by(reader: r)
            if !current_reader.reader_books.find_by(book: b)
              @books << b;
            end
          end
        }
      end
    }

    @save_books = @books.clone
    @found = true
      if params[:search]
        @books.each { |x|
          if !x.name.include?(params[:search])
            @books.delete(x)
          end
        }
        if @books.empty?
          @found = false
          @books = @save_books
        end
      end
  end

  def mybooks
    if !logged_in?
      store_location
      redirect_to root_path
      return
    end
    @reader = Reader.find(params[:id])
    @books = []
    @fount = true
    if (['Want to read', 'Read', 'Reading']).include?(params[:commit])
      Book.all.each { |b| 
        if b.reader_books.find_by(reader: @reader)
          if b.reader_books.find_by!(reader: @reader).status == params[:commit]
            @books << b;
          end
        end
      }

      if @books.empty?
        @fount = false        #я не ошибся, там правла t
        Book.all.each { |b| 
          if b.reader_books.find_by(reader: @reader)
            @books << b;
          end
        }
      end
    else
      Book.all.each { |b| 
        if b.reader_books.find_by(reader: @reader)
          @books << b;
        end
      }
    end

    @save_books = @books.clone
    @found = true
      if params[:search]
        @books.each { |x|
          if !x.name.include?(params[:search])
            @books.delete(x)
          end
        }
        if @books.empty?
          @found = false
          @books = @save_books
        end
      end
  end

  def new
    if check==0
      return
    end
  	@book = Book.new
    @authors = Author.all
  end 

  def show
    @book = Book.find(params[:id])
    @authors = Author.all
    @review = current_reader.reviews.build if logged_in?

  end

  def edit
    if check==0
      return
    end
    @book = Book.find(params[:id])
  end

  def update
    if check==0
      return
    end
    @book = Book.find(params[:id])

    Author.all.each { |a| 
      if a.author_books.find_by(book: @book)
          a.author_books.find_by!(book: @book).destroy
      end
    }

    if @book.update(book_params)
        @author = adv_params[:authors]
        @author = @author.split(',')
        @author.each {|each_auth|
          Author.all.each { |a| 
            if a.name == each_auth
              @author_book = @book.author_books.build(author: a)
              if !@author_book.save
                redirect_to root_path
              end
            end
          }
        }
        redirect_to @book
      else
        render 'edit'
      end
  end

  def create
    if check==0
      return
    end
    @book = Book.new(book_params)

      if @book.save
        @author = adv_params[:authors]
        @author = @author.split(',')
        @author.each {|each_auth|
          Author.all.each { |a| 
            if a.name == each_auth
              @author_book = @book.author_books.build(author: a)
              if !@author_book.save
                redirect_to root_path
              end
            end
          }
        }
        redirect_to @book
      else
        render 'new'
      end
  end

  def destroy
    if check==0
      return
    end
    @book = Book.find(params[:id])
    @book.destroy
 
    redirect_to books_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :year, :ISBN, :genre, :rating_amount, :rating_average)
    end

    def adv_params
        params.require(:book).permit(:name, :year, :ISBN, :genre, :rating_amount, :rating_average, :authors)
    end

    def check
      if !logged_in?
        store_location
        redirect_to root_path 
        return 0
      elsif current_reader.name != "admin"
        redirect_to root_path 
        return 0
      else
        return 1
      end
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<% provide(:title, "Edit" + @book.name) %>

<h1>Editing "<%= @book.name %>" info</h1>
<div class="row">
<%= form_for :book, url: book_path(@book), method: :patch do |f| %>
 
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@book.errors.count, "error") %> prohibited
        this book from being saved:
      </h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "textfield"  %>
  </p>
  <p>
      <%= f.label :authors %><br>
      <%= f.text_field :authors, class: "form-control textfield" %>
    </p>
  <p>
    <%= f.label :year %><br>
    <%= f.text_field :year, class: "textfield"  %>
  </p>
  <p>
    <%= f.label :ISBN %><br>
    <%= f.text_field :ISBN, class: "textfield"  %>
  </p>
  <p>
    <%= f.label :genre %><br>
    <%= f.text_field :genre, class: "textfield"  %>
  </p>
  <p>
    <%= f.submit 'Save', class: "btn flat_button" %>
  </p>
<div class="center"><%= link_to 'Discard and go back', books_path, class: "link" %></div>
<% end %>
</div>

app/views/books/index.html.erb
<% provide(:title, 'Books') %>
  <p id="notice"><%= notice %></p>

  <div class="main">

  <h1>In need of a book?</h1>
  <div class="row">
  
      <%= form_tag(books_path, :method => "get", id: "search-form") do %>
      <div class="col-md-8 inline">
        <%= text_field_tag :search, params[:search], placeholder: "What are you looking for?", class: 'form-control textfield' %>
      </div>
      <div class="col-md-4 inline">
        <%= submit_tag "Search", class: "btn flat_button" %>
      </div>
      <% end %>
  </div>
  <% if !@found %>
    <div id="notfoundmessage"><p>There are no books containing the term(s) <%= params[:search] %>. Here is the list of all books</p></div>
  <% end %>

  <div class="table_headings">
  <% if logged_in? %>
    <% if current_reader.name == "admin" %>
      <div class="row">
        <div class="col-md-4 inline">Name</div>
        <div class="col-md-1 inline">Year</div>
        <div class="col-md-2 inline">ISBN</div>
        <div class="col-md-3 inline">Genre</div>
        <div class="col-md-1 inline">Rating</div>
      </div>
    <% else %>
      <div class="row">
        <div class="col-md-4 inline">Name</div>
        <div class="col-md-1 inline">Year</div>
        <div class="col-md-2 inline">ISBN</div>
        <div class="col-md-3 inline">Genre</div>
        <div class="col-md-1 inline">Rating</div>
      </div>
    <% end %>
  <% else %>
    <div class="row">
      <div class="col-md-4 inline">Name</div>
      <div class="col-md-1 inline">Year</div>
      <div class="col-md-2 inline">ISBN</div>
      <div class="col-md-3 inline">Genre</div>
      <div class="col-md-1 inline">Rating</div>
    </div>
  <% end %>   
  </div>
    <div class="table_items">
    <% @books.each do |book| %>
    <% if logged_in? %>
      <% if current_reader.name == "admin" %>
      <div class="row">
        <div class="col-md-4 inline"><%= link_to book.name, book, class: "link" %></div>
        <div class="col-md-1 inline"><%= book.year %></div>
        <div class="col-md-2 inline"><%= book.ISBN %></div>
        <div class="col-md-3 inline"><%= book.genre %></div>
        <div class="col-md-1 inline"><%= book.rating_average.round(2) %></div>
        <div class="col-md-1 inline">
          <div class="inline">
            <%= link_to edit_book_path(book) do %>
            <span class="glyphicon glyphicon-pencil right"></span>
            <% end %> 
          </div> 
          <div class="inline">
            <%= link_to book_path(book),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-trash right"></span>
            <% end %>  
          </div>    
        </div> 
      </div> 
      <% else %>
      <div class="row">
        <div class="col-md-4 inline"><%= link_to book.name, book, class: "link" %></div>
        <div class="col-md-1 inline"><%= book.year %></div>
        <div class="col-md-2 inline"><%= book.ISBN %></div>
        <div class="col-md-3 inline"><%= book.genre %></div>
        <div class="col-md-1 inline center"><%= book.rating_average.round(2) %></div>
      </div>
      <% end %>
    <% else %>
      <div class="row">
        <div class="col-md-4 inline"><%= link_to book.name, book, class: "link" %></div>
        <div class="col-md-1 inline"><%= book.year %></div>
        <div class="col-md-2 inline"><%= book.ISBN %></div>
        <div class="col-md-3 inline"><%= book.genre %></div>
        <div class="col-md-1 inline center"><%= book.rating_average.round(2) %></div>
      </div>
    <% end %>
    <% end %>
    </div>
  </div>
  <br>

app/views/books/mybooks.html.erb
  <div class="main">
<% if @reader==current_reader %>
  <% provide(:title, 'Your books') %>
<% else %>
  <% provide(:title, @reader.name+"'s books") %>
<% end %>

<p id="notice"><%= notice %></p>

<% if @reader==current_reader %>
  <h1>Your books</h1>
<% else %>
  <h1><%= @reader.name %>'s books</h1>
<% end %>
  <div class="row">
      <%= form_tag("/readers/#{@reader.id}/mybooks", :method => "get", id: "search-form") do %>
      <div class="col-md-8 inline">
      <%= text_field_tag :search, params[:search], placeholder: "What are you looking for?", class: 'form-control textfield' %>
    </div>
    <div class="col-md-4 inline">
      <%= submit_tag "Search", class: "btn flat_button" %>
          </div>
      <% end %>
  </div>

  <%= form_for (:book) do |f| %>
    <div class="row">
      <div class="col-md-4 inline"> <%= f.submit :'Want to read', class: "btn flat_button books" %> </div>
      <div class="col-md-4 inline"> <%= f.submit :'Reading', class: "btn flat_button books" %> </div>
      <div class="col-md-4 inline"> <%= f.submit :'Read', class: "btn flat_button books" %> </div>
    </div>
  <% end %>

  <% if !@found %>
    <p>There are no books containing the term(s) <%= params[:search] %>. Here is the list of all  your books</p>
  <% end %>
  <% if !@fount %>
    <p>There are no books with chosen status. Here is the list of all your books</p>
  <% end %> 
  <p></p>
  <div class="table_headings">
    <div clas="row">
      <div class="col-md-5 inline">Name</div>
      <div class="col-md-1 inline">Year</div>
      <div class="col-md-2 inline">ISBN</div>
      <div class="col-md-3 inline">Genre</div>
      <div class="col-md-1 inline center">Rating</div>
    </div>
  </div>
    <div class="table_items">
      <% @books.each do |book| %>
      <div class="row">
        <div class="col-md-5 inline"><%= link_to book.name, book, class: "link" %></div>
        <div class="col-md-1 inline"><%= book.year %></div>
        <div class="col-md-2 inline"><%= book.ISBN %></div>
        <div class="col-md-3 inline"><%= book.genre %></div>
        <div class="col-md-1 inline"><%= book.rating_average.round(2) %></div>
      </div>
      <% end %>
    </div>
      <br>
  </div>
  <br>

app/views/books/new.html.erb
<% provide(:title, "New book") %>
<div class="main">
<h1>New book</h1>
  <%= form_for :book, url: books_path do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control textfield" %>
    </p>
   
    <p>
      <%= f.label :authors %><br>
      <%= f.text_field :authors, class: "form-control textfield" %>
    </p>

    <p>
      <%= f.label :year %><br>
      <%= f.text_field :year, class: "form-control textfield" %>
    </p>

    <p>
      <%= f.label :ISBN %><br>
      <%= f.text_field :ISBN, class: "form-control textfield" %>
    </p>

    <p>
      <%= f.label :genre %><br>
      <%= f.text_field :genre, class: "form-control textfield" %>
    </p>
   
    <p>
      <%= f.submit :'Add book', class: "btn flat_button" %>
    </p>
  <% end %>
</div>

app/views/books/recom.html.erb
<% if @reader==current_reader %>
  <% provide(:title, 'Your recommendations') %>
<% else %>
  <% provide(:title, @reader.name+"'s recommendations") %>
<% end %>

<p id="notice"><%= notice %></p>
  <div class="main">
<h1> Recommendations </h1>
  <div class="row">
      <%= form_tag("/readers/#{@reader.id}/recom", :method => "get", id: "search-form") do %>
      <div class="col-md-8 inline">
      <%= text_field_tag :search, params[:search], placeholder: "What are you looking for?", class: 'form-control textfield' %>
    </div>
    <div class="col-md-4 inline">
      <%= submit_tag "Search", class: "btn flat_button" %>
          </div>
      <% end %>
  </div>
<% if !@found %>
  <div><p>There are no books containing the term(s) <%= params[:search] %>. Here is the list of all recommended books</p></div>
<% end %>
  <div class="table_headings">
    <div class="row">
      <div class="col-md-4 inline">Name</div>
      <div class="col-md-1 inline">Year</div>
      <div class="col-md-2 inline">ISBN</div>
      <div class="col-md-3 inline">Genre</div>
      <div class="col-md-2 inline">Rating</div>
    </div>
  </div>
  <div class="table_items">
    <% @books.each do |book| %>
      <div class="row">
        <div class="col-md-4 inline"><%= link_to book.name, book, class: "link" %></div>
        <div class="col-md-1 inline"><%= book.year %></div>
        <div class="col-md-2 inline"><%= book.ISBN %></div>
        <div class="col-md-3 inline"><%= book.genre %></div>
        <div class="col-md-2 inline"><%= book.rating_average.round(2) %></div>
      </div>
    <% end %>
  </div>
<br>
</div>

app/views/books/show.html.erb
<% provide(:title, @book.name) %>
<div class="main">
  <h1><%= @book.name %>
  <% if logged_in? %>
    <% if current_reader.name=="admin" %>
      <div class="inline">
        <p>
          <%= link_to edit_book_path(@book) do %>
            <span class="glyphicon glyphicon-edit"></span>
          <% end %>
        </p>
      </div>
      <% end %>
     <% end %>
  </h1>
    <p>
      <strong>Authors:</strong>
      <% @authors.each do |author| %>
        <% if @book.author_books.find_by(author: author)%>
          <%= author.name %>
        <% end %>
      <% end %>
    </p>

    <p>
      <% unless @book.year == '' %>
        <strong>Year:</strong>
        <%= @book.year %>
      <% end %>
    </p>
      <p>
        <% unless @book.ISBN == '' %>
          <strong>ISBN:</strong>
          <%= @book.ISBN %>
        <% end %>
      </p>

  <p>
    <% unless @book.genre == '' %>
      <strong>Genre:</strong>
      <%= @book.genre %>
    <% end %>
  </p>

    <p>
    <% if @book.reader_books.find_by(reader: current_reader) %>
      <strong>Status:</strong>
      <%= @book.reader_books.find_by!(reader: current_reader).status %>
    <% else %>
      <strong>Status: none</strong>
    <% end %>
  </p>

  <% if logged_in? %>
    <% if @book.reader_books.find_by(reader: current_reader) %>
      <% if @book.reader_books.find_by!(reader: current_reader).rating==0 %>
        <%= form_for @book.reader_books.build do |f| %>     
        <%= f.hidden_field :book_id, value: @book.id %>
          <strong><p class="inline">Rate it:</p></strong>
          <% for i in 1..10 do %>
            <div class="rate inline">
              <%= button_tag(type: 'submit', name: "commit", value: i.to_s, class: "bttn") do %>☆
            </div>
          <% end %>
        <% end %>
        <% end %>
      <% else %>
        <p><strong>Your rate:</strong> <%= @book.reader_books.find_by!(reader: current_reader).rating %></p>
      <% end %>
    <% end %>
  <% end %>

  <% if logged_in? %>
      <%= form_for @book.reader_books.build do |f| %>
      <%= f.hidden_field :book_id, value: @book.id %>
        <div class="row">
          <% if @book.reader_books.exists?(reader: current_reader) == false %>
            <div class="col-md-4"> <%= f.submit :'Want to read', class: "btn flat_button" %> </div>
            <div class="col-md-4"> <%= f.submit :'Reading', class: "btn flat_button" %> </div>
            <div class="col-md-4"> <%= f.submit :'Read', class: "btn flat_button" %> </div> 
          <% else %>
            <% if @book.reader_books.find_by!(reader: current_reader).status == 'Want to read' %>
              <div class="col-md-4"> <%= f.submit :'Want to read', class: "btn flat_button disabled" %> </div>
              <div class="col-md-4"> <%= f.submit :'Reading', class: "btn flat_button" %> </div>
              <div class="col-md-4"> <%= f.submit :'Read', class: "btn flat_button" %> </div>
            <% elsif @book.reader_books.find_by!(reader: current_reader).status == 'Reading' %>
              <div class="col-md-4"> <%= f.submit :'Want to read', class: "btn flat_button disabled" %> </div>
              <div class="col-md-4"> <%= f.submit :'Reading', class: "btn flat_button disabled" %> </div>
              <div class="col-md-4"> <%= f.submit :'Read', class: "btn flat_button" %> </div>
            <% elsif @book.reader_books.find_by!(reader: current_reader).status == 'Read' %>
              <div class="col-md-12"><p><strong>Read it? Tell everyone about your experience. Leave a comment!</strong></p></div>
            <% end %>      
          <% end %>
        </div>
      <% end %>
  <% end %>

  <% if logged_in? %>
    <% unless @book.recommendations.find_by(reader: current_reader) %>
      <br><br>
      <div class="col-md-8 left"><p><i>Did you like it?</i> Recommend to your followers!</p></div>
      <%= form_for @book.recommendations.build do |f| %>
        <%= f.hidden_field :book_id, value: @book.id %>
        <div class="col-md-4"><i><%= f.submit :'Recommend', class: "btn flat_button recommend" %></i></div>
      <% end %>
    <% end %>
  <% end %>
  <br>
  <h2 class="center comments"> Comments </h2>
  <div class="row">  
    <% @book.reviews.each do |review| %>
        <div class="col-md-3">
          <p><%= review.reader.name %></p>
        </div>
        <div class="col-md-9">
          <p><%= review.text %></p>
        </div>
        <p class="center comment_separator">__________________________________</p>
    <% end %>
  </div>

  <% if logged_in? %>
    <% unless @book.reviews.find_by(reader: current_reader) %>
      <%= form_for @book.reviews.build do |f| %>
        <%= f.text_area :text, :rows => 5, class: "form-control textfield"  %>
        <%= f.hidden_field :book_id, value: @book.id %>
        <%= f.submit :'Add comment', class: "btn flat_button" %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <br>