config/routes.rb
Rails.application.routes.draw do


  root 'sessions#root'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'  
  get '/signup', to: 'readers#new'
  post '/signup', to: 'readers#create'

  get '/readers/:id/recom', to: 'books#recom'
  get '/readers/:id/foll', to: 'readers#foll'
  post '/readers/:id/foll', to: 'readers#foll'
  get '/readers/:id/mybooks', to: 'books#mybooks'
  post '/readers/:id/mybooks', to: 'books#mybooks'


  resources :author_books
  resources :reader_books
  resources :recommendations
  resources :relationships
  resources :readers
  resources :authors
  resources :books
  resources :reviews,          only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
</div>
<footer class="footer navbar-fixed-bottom">
  <div class="center">
  	<p class="footer_text">© 2016 Book App</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default header">
  <div class="container">
    <div class="col-md-offset-1">
    <%= link_to "book app", root_path, id: "logo", class: "hvr-sweep-to-right" %>
    <nav>
      <ul class="nav navbar-nav navbar-right md-offset-right-1">
        <li><%= link_to "Books", books_path %></li>
        <li><%= link_to "Authors", authors_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Readers", readers_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_reader.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_reader %></li><!-- current_user-->
              <li><%= link_to "Recommendations", "/readers/#{current_reader.id}/recom" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li><!-- login_path-->
        <% end %>
      </ul>
    </nav>
  </div>
</div>
</header>

app/views/layouts/_rails_default.html.erb
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="/assets/bootstrap.min.js"></script>
    <script src="/assets/bootstrap.js"></script>
    <link rel="stylesheet" src="/assets/bootstrap.css">
    <link rel="stylesheet" src="/assets/main.css">
    <link href="/assets/bootstrap.min.css" rel="stylesheet" media="screen">
    <link rel="stylesheet" type="text/css" href="/assets/application.css">

  </head>
  <body>

    <%= render 'layouts/header' %>
      <div class="container">
        <div class="col-md-10 col-md-offset-1 length">
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>

        <%= yield %>
        <%= render 'layouts/footer' %>
        <!--<%= debug(params) if Rails.env.development? %>-->
        </div>
      </div>
  <script>
    $(document).ready(function () {
        $('.dropdown-toggle').dropdown();
    });
  </script>
  </body>
</html>